# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    ./bluetooth.nix
  ];

  hardware.graphics.enable = true;

  services.logind.settings.Login.HandleLidSwitch = "suspend";

  services.libinput.touchpad = {
    disableWhileTyping = true;
    tapping = false;
  };

  boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.loader = {
    systemd-boot.enable = true;
    efi.canTouchEfiVariables = true;
  };

  console = {
    earlySetup = true;
    font = "ter-v32n";
    keyMap = "us";
    packages = with pkgs; [ terminus_font ];
  };

  # use systemd instead of stage 1 script
  boot.initrd.systemd.enable = true;
  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [
    "vfat"
    "fat"
    "nls_cp437"
    "nls_iso8859-1"
    "af_alg"
    "algif_hash"
    "algif_skcipher"
    "af_packet"
    "cmac"
    "rfcomm"
    "bnep"
    "uhid"
    "uinput"
    "tun"
    "nfnetlink"
    "nf_tables"
    "nft_compat"
    "nft_fib"
    "nft_fib_inet"
    "nft_fib_ipv4"
    "nft_fib_ipv6"
    "nft_chain_nat"
    "nft_ct"
    "nft_masq"
    "nft_nat"
    "nf_conntrack"
    "nf_nat"
    "x_tables"
    "xt_conntrack"
    "xt_connmark"
    "xt_mark"
    "xt_MASQUERADE"
    "xt_pkttype"
    "xt_tcpudp"
    "qrtr"
    "qrtr_mhi"
  ];
  boot.kernelModules = [
    "kvm-amd"
    "thinkpad_acpi"
    "af_alg"
    "algif_hash"
    "algif_skcipher"
    "af_packet"
    "cmac"
    "rfcomm"
    "bnep"
    "uhid"
    "uinput"
    "tun"
    "nfnetlink"
    "nf_tables"
    "nft_compat"
    "nft_fib"
    "nft_fib_inet"
    "nft_fib_ipv4"
    "nft_fib_ipv6"
    "nft_chain_nat"
    "nft_ct"
    "nft_masq"
    "nft_nat"
    "nf_conntrack"
    "nf_nat"
    "x_tables"
    "xt_conntrack"
    "xt_connmark"
    "xt_mark"
    "xt_MASQUERADE"
    "xt_pkttype"
    "xt_tcpudp"
    "qrtr"
    "qrtr_mhi"
  ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/c15c0cf2-75d0-4e95-934a-bf4f6ba08f4e";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/FDE5-ECBA";
    fsType = "vfat";
  };

  swapDevices = [ { device = "/dev/disk/by-uuid/cb4a9137-a954-4e85-a983-76d219e52e5a"; } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
